services:
  ################ infrastructure ###########################
  traefik:
    image: traefik:3.1
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: unless-stopped
    environment:
      - ROOT_DOMAIN
      - PUBLIC
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/traefik:/etc/traefik"
      - "./data/traefik:/data/"
    networks:
      - personal-site-ingress
      - connect4-ingress
    profiles:
      - infra
      - all

  postgres:
    image: postgres:16
    container_name: postgres
    user: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    networks:
      - super-bowl-quiz-backend
    profiles:
      - infra
      - all

  ####################### apps ################################
  personal-site:
    image: automationmusician/personal-site:latest
    build: ../personal-site/
    container_name: personal-site
    restart: unless-stopped
    networks:
      - personal-site-ingress
    profiles:
      - app
      - all

  connect4:
    image: automationmusician/connect4:latest
    build: ../connect-4-ai-801/
    container_name: connect4
    environment:
      BASE_PATH: "/connect4"
      MAX_DEPTH: 6
    restart: unless-stopped
    networks:
      - connect4-ingress
    profiles:
      - app
      - all

  #### super bowl quiz ####
  super_bowl_quiz_initialize_database:
    image: postgres:16
    user: postgres
    depends_on: 
      - postgres
    entrypoint: "/mnt/initialize_database.sh"
    environment:
      PGHOST: postgres
      PGPASSWORD: ${POSTGRES_PASSWORD}
      SUPER_BOWL_QUIZ_PGPASSWORD: ${SUPER_BOWL_QUIZ_PGPASSWORD}
    networks:
      - super-bowl-quiz-backend
    volumes:
      - "../super-bowl-quiz/database_setup:/mnt"
    profiles:
      - app
      - all

networks:
  personal-site-ingress:
    name: personal-site-ingress
  connect4-ingress:
    name: connect4-ingress
  super-bowl-quiz-backend:
    name: super-bowl-quiz-backend

volumes:
  pgdata:
    name: pgdata