http:
  routers:
    personal-site:
      service: personal-site-website-orchestrator@docker
      rule: Host(`joshuafishman.duckdns.org`)
      entrypoints: websecure
      tls:
        certresolver: defaultCertResolver